import os

MODELS = ['cgan', 'cwgan', 'gan_with_twist']
MAIN_DATA_DIR = 'Data'
DIABETES_PATH = os.sep.join([MAIN_DATA_DIR, 'diabetes.arff'])
GERMAN_CREDIT_PATH = os.sep.join([MAIN_DATA_DIR, 'german_credit.arff'])

MAIN_MODELS_DIR = 'models'

PERFORM_GRID_SERACH = False
DATASET = 'diabetes'
GAN_MODE = MODELS[2]

SEED = 42
BATCH_SIZE = 64
N_EPOCHS = 1
LATENT_NOISE_SIZE = 30
GENERATOR_LR = 0.00002
CRITIC_LR = 0.00002
CRITIC_DROPOUT = 0.2
CRITIC_STEPS = 3
IS_LABEL_CONDITIONAL = True
NUM_OF_RANDOM_SAMPLES_PART1 = 100
NUM_OF_RANDOM_SAMPLES_PART2 = 1000
